server:
  port: 9016
  
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      mvc:
        routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/userService/**
          
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
          - Path=/hotelService/**
          
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
          - Path=/ratingService/**
          
        - 
eureka:
  instance:
    ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka